name: mini_project_application
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.1 <4.0.0'

dependencies: 
  cloud_firestore: ^4.17.2
  cupertino_icons: ^1.0.6
  firebase_auth: ^4.19.4
  firebase_core: ^2.30.1
  get: 4.6.6
  image_picker: ^1.1.1
  firebase_storage: ^11.6.11
  get_cli: ^1.8.1
  google_fonts: ^6.2.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
    - assets/img/
  uses-material-design: true

